### PR TITLE
Persistent apps selection

### PR DESCRIPTION
**Pull request by sorge13248**
Automatically saves selected apps to localStorage, thus persisting selection when page gets closed or refreshed.

### CODE REVIEW

**Comment by MehediH** [comment]
Hey, this looks great! But we need to consider one thing: when do we clear the selection? Especially after a user has generated a script, we should clear the selection of apps.

**Comment by sorge13248** [comment]
Hi there, that's a good point! I could implement an auto-clear feature that clears selection after the script has been generated.
What do you think?

**Comment by MehediH** [comment]
Yes that would be much better...but another thing that just hit me: how can we sync the app selections between different tabs? If a user selects different apps in different tabs, that would mess with the localstorage

**Comment by sorge13248** [comment]
A quick search lead me to this article: https://medium.com/@mfreundlich1/syncing-localstorage-across-multiple-tabs-cb5d0b1feaab

We could implement that event listener and every time it occurs, we reload apps from localStorage.

**Comment by MehediH** [comment]
Yes, that does seem like a possible solution...would love to see this in action if you can make the changes :)

**Comment by sorge13248** [comment]
Actually I'm having trouble implementing the storage event, as it does not seem to trigger.
It needs further researches and testing, but right now I'm busy at work.

About the auto-clear of selected apps, I implemented it. Let me know if it is a good solution or if it needs any changes :)

**Pull request closed without merging**
