### PR TITLE
Add github action ci on pull request and merge to master

### PR DESCRIPTION
**Pull request by usmslm102**
- Add github action ci with trigger on push to master and pull request to master
- Add CI badge on read me file

### CODE REVIEW

**Comment by MehediH** [comment]
Hi! Thank you for the PR, but I am failing to understand what the point of this is...? If you could clarify why we need the Node CI, that would be great.

**Comment by usmslm102** [comment]
It will help you to maintain the code quality. If someone is contributing and make some mistakes in code. The CI will fail and they can go and check the error in CI build. I agree you are using vercel for continous deployment but if I'm not wrong the contributer can see the logs.

**Comment by MehediH** [comment]
Good point! Just to clarify/confirm, this will not automatically merge PRs to master, right?

**Comment by usmslm102** [comment]
No. It will not merge PR without your approval. But it will not allow you to complete PR if the CI fails.

**Comment by MehediH** [comment]
Awesome, ty!

**Pull request merged**
